#add_newline = false

#[line_break]
##disabled = true

#[directory]
#truncation_length = 8

#[golang]
#symbol = " "

#[aws]
#style = "bold blue"
#symbol = " "
#displayed_items = "region"

#[aws.region_aliases]
#ap-southeast-2 = "au"
#us-east-1 = "va"

#[kubernetes]
#symbol = "⛵ "
#style = "blue"
#disabled = true
##disabled = false

#[git_branch]
#symbol = " "

#[git_status]
#conflicted = "🏳"
##ahead = "🏎💨"
#behind = "😰"
#diverged = "😵"
#stashed = "📦"
#staged.value = "++"
#staged.style = "green"
#staged_count.enabled = true
#staged_count.style = "green"
##renamed = "👅"
#deleted = "🗑"
#modified_count = true
#show_sync_count = true
##modified = "📝"
##untracked = "🤷‍"

#[ruby]
#symbol = " "

#[rust]
#symbol = " "
##symbol = "🦀"
